/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DESAFIO ;

import java.util.Scanner;

public class App{
    public static void main(String[] args) {
    Scanner scanner = new Scanner(System.in);
    
            Paladino paladino = new Paladino();
            Barbaro barbaro = new Barbaro();
            Feiticeiro feiticeiro = new Feiticeiro();
            Inimigo1 inimigo1 = new Inimigo1();
            Inimigo2 inimigo2 = new Inimigo2();
            Boss boss = new Boss();
            Menu meuMenu = new Menu();
            historia historia = new historia();
            
         System.out.println(historia.herois());
         System.out.println(meuMenu.menu);
         int escolha = scanner.nextInt();
            
            System.out.println("Escolha o nome do seu personagem\n");
            String nomePersonagem = scanner.nextLine();
    
            System.out.println("Muito prazer " + nomePersonagem + ", Bem vindo ao "
                    + ""
                    + "AVENTURAS AVENTURADAS."
                    + ""
                    + "SUA JORNADA COMEÇA AGORA! \n");
            
           Habilidades personagemEscolhido = null;
           
           switch(escolha){
               
                 case 1: 
                 personagemEscolhido = paladino;
                 System.out.println("Sua escolha foi o Paladino\n"
                         + ""
                         + "SUA JORNADA COMO Sir Tharion, o Paladino Azarado COMECA AGORA\n" +
                         historia.introducao()
                         );
                 break;
                
                 case 2:  
                 personagemEscolhido = barbaro;
                 System.out.println("Sua escolha foi o Barbaro\n"
                         + ""
                         + "SUA JORNADA COMO Grug, o Bárbaro Gourmet COMECA AGORA\n" +
                         historia.introducao()
                         );

                 break;
                 
                 case 3:
                 personagemEscolhido = feiticeiro;
                 System.out.println("Sua escolha foi a Feiticeiro\n"
                         + ""
                         + "SUA JORNADA COMO Mirela, a Feiticeira Sarcástica COMECA AGORA\n" +
                         historia.introducao()
                         );
                               
                 
                 break;
                 
                 default: System.out.println("Escolha alguma opçao válida!!!\n");
           }
           
           System.out.println("Você deseja enfrentar o inimigo ou correr?"
                   + "\n"
                   + "1.Enfrentar \n" 
                   + "2.Correr\n"
           );
            String caminho = scanner.nextLine();
            
            switch(caminho){
                
                case "1": 
                    System.out.println("CAMINHO 1");
                break;
           
                case "2":
                    System.out.println("CAMINHO 2");
                  break;
           
            };
           
           
                        
                        
    }
}

            
            
    
   
    
    
    
    
