/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DESAFIO ;

import java.util.Scanner;

public class App{
    public static void main(String[] args) {
    Scanner scanner = new Scanner(System.in);
    
            Paladino paladino = new Paladino();
            Barbaro barbaro = new Barbaro();
            Feiticeiro feiticeiro = new Feiticeiro();
            Inimigo1 inimigo1 = new Inimigo1();
            Inimigo2 inimigo2 = new Inimigo2();
            Boss boss = new Boss();
            Menu meuMenu = new Menu();
            historia historia = new historia();
            golpeEspecial quantidadeGolpe = new golpeEspecial();
            Bandagem bandagem = new Bandagem();
            
            System.out.println("Qual e seu nome? \n");
            String nomePersonagem = scanner.nextLine();
    
            System.out.println("\nMuito prazer " + nomePersonagem + ". \n\n             Bem vindo ao \n\n"
                    + ""
                    + "--------AVENTURAS AVENTURADAS--------\n"
                    + "    Desafios e lendas em cada passo! \n\n"
                    + "------SUA JORNADA COMECA AGORA!------ \n");
            
         System.out.println("");
           System.out.println("Clique enter para comecar a historia!");
           String enterhistoria = scanner.nextLine();
           System.out.println(historia.introducao());
            
            System.out.println("");
            System.out.println("Esta na hora de escolher sua classe, irei dar uma breve intruducao para cada uma!");
            System.out.println("\nClique enter para escolher!");
            String enter = scanner.nextLine();
            System.out.println("");
                        
        System.out.println(historia.herois());
        System.out.println("Escolha sua classe: \n");
        int escolha = scanner.nextInt();
        
            
           Habilidades personagemEscolhido = null;
           
           switch(escolha){
               
                 case 1: 
                 personagemEscolhido = paladino;
                 System.out.println("\nSua escolha foi o Paladino\n\n"
                         + ""
                         +"--Sir Tharion, o Paladino Azarado --"
);
                 break;
                
                 case 2:  
                 personagemEscolhido = barbaro;
                 System.out.println("\nSua escolha foi o Barbaro\n\n"
                         + ""
                         + "--Grug, o Barbaro Gourmet--"
);

                 break;
                 
                 case 3:
                 personagemEscolhido = feiticeiro;
                 System.out.println("\nSua escolha foi a Feiticeiro\n\n"
                         + ""
                         + "--Mirela, a Feiticeira Sarcastica--"
                         );
                               
                 
                 break;
                 
                 default: System.out.println("\nComo opcao invalida, eu mesmo irei escolher seu personagem, que sera o Barbaro.");
               //fazer um sorteio para escolher um personagem aleatorio caso escolha alguma opçao invalida!
                 personagemEscolhido = barbaro;
           }
           
            int numero1 = 0;
         int numero2 = 0;
         int numero3 = 0;
         int numero4 = 0;

        if (personagemEscolhido instanceof Barbaro) {
            numero1 = 3;
            numero2 = 4;
            numero3 = 2;
           
        } else if (personagemEscolhido instanceof Paladino) {
            numero1 = 4;
            numero2 = 2;
            numero3 = 1;

        } else if (personagemEscolhido instanceof Feiticeiro) {
            numero1 = 2;
            numero2 = 1;
            numero3 = 3;
 
        } 
 
        String palavra1 = (numero1 == 1) ? "dado" : "dados";
        String palavra2 = (numero2 == 1) ? "dado" : "dados";
        String palavra3 = (numero3 == 1) ? "dado" : "dados";
        
    
        System.out.println("");
        System.out.println("Agora defina seus atributos rolando os dados!\n");
        
        
        System.out.println("---Voce tem " + numero1 +" "+ palavra1 + " para o dano---\n");
        Scanner scanner1 = new Scanner(System.in);
        int ArmazenaDano = personagemEscolhido.Dano();
        
        System.out.println("Voce quer rolar os dados? (s/n): ");
        String resposta1 = scanner1.nextLine();
        if (resposta1.equals("s")) {
           System.out.println("Dano: " + ArmazenaDano);
        } else {
            System.out.println("---Essa opcao esta invalida, irei rolar os dados por voce!---");
            System.out.println("Dano: " + ArmazenaDano);
        }
        System.out.println("");
         /*aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa*/
        
          System.out.println("---Voce tem " +numero2 +" "+palavra2 + " para a vida---\n");
          Scanner scanner2 = new Scanner(System.in);
        int ArmazenaVida = personagemEscolhido.Vida();
          
        System.out.println("Voce quer rolar os dados? (s/n): ");
        String resposta2 = scanner2.nextLine();
        if (resposta2.equals("s")) {
           System.out.println("Vida: " + ArmazenaVida);
        } else {
            System.out.println("---Essa opcao nao esta valida, irei rolar os dados por voce!---");
            System.out.println("Vida: " + ArmazenaVida);
        }
        System.out.println("");
        /*aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa*/
        
        
        System.out.println("---Voce tem " + numero3 +" "+ palavra3 + " para a mana---\n");
        Scanner scanner3 = new Scanner(System.in);
        int ArmazenaMana = personagemEscolhido.Mana();
        
        System.out.println("Voce quer rolar os dados? (s/n): ");
        String resposta3 = scanner3.nextLine();
        if (resposta3.equals("s")) {
           System.out.println("Mana: " + ArmazenaMana);
        } else {
            System.out.println("---Esta opcao nao esta valida, irei rolar os dados por voce!---");
             System.out.println("Mana: " + ArmazenaMana);
        }
       System.out.println("");
        /*aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa*/
        
        
        System.out.println("Aqui estao seus atributos:\n");
        System.out.println("-----------");
        System.out.println("Nome: " + nomePersonagem);
        System.out.println("Dano: " + ArmazenaDano);
        System.out.println("Vida: " + ArmazenaVida);
        System.out.println("Mana: " + ArmazenaMana);
        System.out.println("-----------");
       
        
           System.out.println("\nVoce embarcou em sua aventura, mas possui uma duvida: qual lado seguir?\n");
System.out.println("1. Esquerda");
System.out.println("2. Direita\n");

int caminhoEsc = 0; // Inicializamos com um valor padrão
boolean escolhaValida = false;

while (escolhaValida != true) {
 
    String caminho = scanner.nextLine(); // Leia como String para evitar erros de tipo
    
switch(caminho){
    case "1":
        caminhoEsc = 1;
        escolhaValida = true;
    break;
    
    case "2":
        caminhoEsc = 2;
        escolhaValida = true;
        break;
                
                default:
        System.out.println("Por favor, escolha 1 ou 2.");
        break;
    }
}

// Processa o caminho escolhido
if (caminhoEsc == 1) {
    System.out.println("Voce escolheu o caminho da esquerda!");
    // Continue a lógica para o caminho da esquerda...
} else if (caminhoEsc == 2) {
    System.out.println("Voce escolheu o caminho da direita!");
    // Continue a lógica para o caminho da direita...
}

        //--------------------------------------------------------------------------------------------------------------------------------------------
        
       if (caminhoEsc == 1){

            System.out.println("\n\n------ Voce encontrou um inimigo ------\n");
            System.out.println(inimigo1.descricao);
           
        while( inimigo1.vida > 0 && ArmazenaVida > 0){
            
            System.out.println("");
            System.out.println("Escolha uma uma das opcoes de ataque!");
            System.out.println("1. Atacar");
            System.out.println("2. Golpe Especial");
            System.out.println("3. Usar Bandagem");
            System.out.println("4. Fugir");
            int escolha1 = scanner.nextInt();
            
            int danoAtacar;
            int danoBandagem;
            int danoInimigo1;
            
            
            
            
             switch (escolha1) { //escolha do menu de habilidades
                 
                case 1: 
                    if (ArmazenaMana > 0){
                    System.out.println("");
            
             personagemEscolhido.Atacar();
            System.out.println("");
            danoAtacar = inimigo1.vida - ArmazenaDano;
            inimigo1.vida = danoAtacar;
            System.out.println("O inimigo recebeu " + ArmazenaDano + " de dano e esta com " + inimigo1.vida+ " de vida!"); // Metodo de Atacar
            
           ArmazenaMana = ArmazenaMana - 1; // retira a energia do personagem apos o ataque
           
        
           
            if (inimigo1.vida > 0 ){
            
            danoInimigo1 = ArmazenaVida - inimigo1.dano;
            ArmazenaVida = danoInimigo1;
            System.out.println("");
            System.out.println("O seu inimigo te atacou e causou " + inimigo1.dano + " de dano!");
            System.out.println("Agora voce esta com " + ArmazenaVida + " de vida!");
            System.out.println("");
            }
            } else {
                    System.out.println("Voce nao tem mais energia!");
                    }
            break;
            
              //---------------------------------------------------------------------------------------------------------------------------
            
                case 2:
                    if(quantidadeGolpe.quantidadeGP > 0){
                     personagemEscolhido.golpeEspecial();
                    quantidadeGolpe.usarGolpe();
                    System.out.println("");
            int danoGP = inimigo1.vida - quantidadeGolpe.danoEspecial;
            inimigo1.vida = danoGP;
            System.out.println("O inimigo recebeu " + quantidadeGolpe.danoEspecial + " de dano e esta com " + inimigo1.vida + " de vida!");
                             
            //aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
         if (inimigo1.vida > 0 ){   
            danoInimigo1 = ArmazenaVida - inimigo1.dano;
            ArmazenaVida = danoInimigo1;
            System.out.println("");
            System.out.println("O seu inimigo te atacou e causou " + inimigo1.dano + " de dano!");
            System.out.println("Agora voce esta com " + ArmazenaVida + " de vida!");
            System.out.println("");
            }
                    } else {
                    System.out.println("Voce nao tem mais golpe especial!");
                    }
                    break;
        
               //---------------------------------------------------------------------------------------------------------------------------
                case 3:
                     if (bandagem.quantidadeBandagem > 0) {
                    personagemEscolhido.UsarBandagem(); //mensagem
                    bandagem.BandagemUsada(); //diminui a quantidade
            danoBandagem = ArmazenaVida + bandagem.vidaBandagem; //cura a vida
            ArmazenaVida = danoBandagem; //nova vida
            System.out.println("Voce recebeu mais " + 15 + " de vida!");
            System.out.println("Agora voce esta com " + ArmazenaVida + " de vida!");
            
            if (inimigo1.vida > 0 ){
            danoInimigo1 = ArmazenaVida - inimigo1.dano;
            ArmazenaVida = danoInimigo1;
            System.out.println("");
            System.out.println("O seu inimigo te atacou e causou " + inimigo1.dano + " de dano!");
            System.out.println("Agora voce esta com " + ArmazenaVida + " de vida!");
            System.out.println("");
            }
                    } else {
                    System.out.println("Voce nao tem mais bandagens!");
                    }
                    break;
                    
                    
                case 4:
                    personagemEscolhido.Fugir();
                    System.out.println("Voce nao conseguiu fugir e acabou sendo ferido!");
                   
                    if (inimigo1.vida > 0 ){
            danoInimigo1 = ArmazenaVida - inimigo1.dano;
            ArmazenaVida = danoInimigo1;
            System.out.println("");
            System.out.println("O seu inimigo te atacou e causou " + inimigo1.dano + " de dano!");
            System.out.println("Agora voce esta com " + ArmazenaVida + " de vida!");
            System.out.println("");
            }
                    break;
                    
                    default:
                    System.out.println("Opcao invalida.");
                    break;
                 }

        }
     
       } else if(caminhoEsc == 2){
   

           System.out.println("\n\n------ Voce encontrou um inimigo ------\n");
            System.out.println(inimigo2.descricao);
           
        while( inimigo2.vida > 0 && ArmazenaVida > 0){
            
            System.out.println("");
            System.out.println("Escolha uma uma das opcoes de ataque!");
            System.out.println("1. Atacar");
            System.out.println("2. Golpe Especial");
            System.out.println("3. Usar Bandagem");
            System.out.println("4. Fugir");
            int escolha1 = scanner.nextInt();
            
            int danoAtacar2;
            int danoBandagem;
            int danoEspecial;
            int danoInimigo2;
            int danoInimigoFinal;
            int armazenaVida;
            int armazenaDano;
            
            
            
             switch (escolha1) { //escolha do menu de habilidades
                 
                case 1: 
                    if (ArmazenaMana > 0){
                    System.out.println("");
            
             personagemEscolhido.Atacar();
            System.out.println("");
            danoAtacar2 = inimigo2.vida - ArmazenaDano;
            inimigo2.vida = danoAtacar2;
            System.out.println("O inimigo recebeu " + ArmazenaDano + " de dano e esta com " + inimigo2.vida+ " de vida!"); // Metodo de Atacar
            
           ArmazenaMana = ArmazenaMana - 1; // retira a energia do personagem apos o ataque
           
        
           
            if (inimigo2.vida > 0 ){
            
            danoInimigo2 = ArmazenaVida - inimigo2.dano;
            ArmazenaVida = danoInimigo2;
            System.out.println("");
            System.out.println("O seu inimigo te atacou e causou " + inimigo2.dano + " de dano!");
            System.out.println("Agora voce esta com " + ArmazenaVida + " de vida!");
            System.out.println("");
            }
            } else {
                    System.out.println("Voce nao tem mais energia!");
                    }
            break;
            
              //---------------------------------------------------------------------------------------------------------------------------
            
                case 2:
                    if(quantidadeGolpe.quantidadeGP > 0){
                     personagemEscolhido.golpeEspecial();
                    quantidadeGolpe.usarGolpe();
                    System.out.println("");
            int danoGP = inimigo1.vida - quantidadeGolpe.danoEspecial;
            inimigo1.vida = danoGP;
            System.out.println("O inimigo recebeu " + quantidadeGolpe.danoEspecial + " de dano e esta com " + inimigo1.vida + " de vida!");
                             
            //aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
         if (inimigo2.vida > 0 ){   
            danoInimigo2 = ArmazenaVida - inimigo1.dano;
            ArmazenaVida = danoInimigo2;
            System.out.println("");
            System.out.println("O seu inimigo te atacou e causou " + inimigo1.dano + " de dano!");
            System.out.println("Agora voce esta com " + ArmazenaVida + " de vida!");
            System.out.println("");
            }
                    } else {
                    System.out.println("Voce nao tem mais golpe especial!");
                    }
                    break;
        
               //---------------------------------------------------------------------------------------------------------------------------
                case 3:
                     if (bandagem.quantidadeBandagem > 0) {
                    personagemEscolhido.UsarBandagem(); //mensagem
                    bandagem.BandagemUsada(); //diminui a quantidade
            danoBandagem = ArmazenaVida + bandagem.vidaBandagem; //cura a vida
            ArmazenaVida = danoBandagem; //nova vida
            System.out.println("Voce recebeu mais " + 15 + " de vida!");
            System.out.println("Agora voce esta com " + ArmazenaVida + " de vida!");
            
            if (inimigo2.vida > 0 ){
            danoInimigo2 = ArmazenaVida - inimigo2.dano;
            ArmazenaVida = danoInimigo2;
            System.out.println("");
            System.out.println("O seu inimigo te atacou e causou " + inimigo2.dano + " de dano!");
            System.out.println("Agora voce esta com " + ArmazenaVida + " de vida!");
            System.out.println("");
            }
                    } else {
                    System.out.println("Voce nao tem mais bandagens!");
                    }
                    break;
                    
                    
                case 4:
                    personagemEscolhido.Fugir();
                    System.out.println("Voce nao conseguiu fugir e acabou sendo ferido!");
                   
                    if (inimigo1.vida > 0 ){
            danoInimigo2 = ArmazenaVida - inimigo2.dano;
            ArmazenaVida = danoInimigo2;
            System.out.println("");
            System.out.println("O seu inimigo te atacou e causou " + inimigo2.dano + " de dano!");
            System.out.println("Agora voce esta com " + ArmazenaVida + " de vida!");
            System.out.println("");
            }
                    break;
                    
                    default:
                    System.out.println("Opcao invalida.");
                    break;
             }
        } //while do caminho 2
       } //caminho 2
       
            int caminho2 = caminhoEsc;
            
        if (caminho2 == 1) {
             if (inimigo1.vida <= 0) {
            System.out.println("-----O inimigo foi derrotado!-----");
            System.out.println("");
            System.out.println("    Voce ficou mais forte e aumentou 2 pontos em seu dano e mana.");
            System.out.println("");
        }} else if ( caminho2 == 2) {
            if (inimigo2.vida <= 0) {
            System.out.println("-----O inimigo foi derrotado-----!");
            System.out.println("");
            System.out.println("   Você recuperou 7 de vida e 2 de Mana");
            System.out.println("");
        }}  
                 
         scanner.nextLine(); // limpa o scanner OBRIGATORIO
         if (ArmazenaVida > 0 ) {
         System.out.println("Clique enter para seguir com a historia!");
          String enter1000 = scanner.nextLine();}
         
         // aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
         // aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
         
         
          if (caminho2 == 1){
              if (inimigo1.vida <= 0) {
            
            System.out.println("Ao derrotar o Zumbi Louco, voce encontrou algo estranho dentro"
                    + " de seu peito: um Fragmento de Cristal Negro, pulsando com energia desconhecida.\n"
                    + "Nele existia uma especie de ponteiro que guiava para algum lugar desconhecido\n"
                    + "Aquilo nao era algo comum e voce sentiu que seria importante em sua jornada.\n" +
" Apos uma enorme jornada sendo guiado pelo desconhecido, voce se depara com um enorme vapor quente,"
                    + " de frente com voce, inevitavelmente, o grande guardiao do mundo metaforico,  \n");
            int danoBonus = ArmazenaDano + 5;
            ArmazenaDano = danoBonus;
            int manaBonus = ArmazenaMana + 2;
            ArmazenaMana = manaBonus;
            }
          
          } else if (caminho2 == 2){
         if (inimigo2.vida <= 0) {
            
            System.out.println("Depois de derrotar o temivel Gigante do Sul, voce seguiu sua jornada\n"
+ " em meio a terras desoladas e cheias de perigos. O sangue do gigante ainda estava\n "
+ "fresco em sua lamina enquanto voce atravessava florestas densas e montanhas \n"
                    + "traicoeiras, onde os ventos sussurravam segredos antigos e proibidos.  \n" +
"Ao longo do caminho, encontrou pequenos desafios: armadilhas naturais, criaturas menores e visoes\n"
                    + " perturbadoras que testaram sua sanidade. Uma noite, ao descansar em uma clareira \n"
                    + "iluminada por uma lua vermelha, um estranho corvo de olhos brilhantes pousou perton"
                    + " de voce. Ele trouxe um aviso: **\"O verdadeiro inimigo espera no coracao do abismo.\n"+
"Guiado pelo corvo, voce desceu ate o vale sombrio, onde os ecos de gritos distantes e a atmosfera sufocante deixaram\n"
                    + " claro que voce estava se aproximando do mal supremo. Ao encontrar o portal ardente que levava ao \n"
                    + "dominio do Capeta Infernal, a temperatura subiu, e uma sensacao de opressao invadiu seu corpo.  \n" +
"\n" +
"Sem escolha, voce atravessou o portal, sabendo que a batalha seguinte seria contra uma entidade que faria o Gigante do\n"
                    + " Sul parecer um simples obstaculo. Sua coragem foi posta a prova mais uma vez.\n"
                    );
            int vidaBonus = ArmazenaVida + 7;
            ArmazenaVida = vidaBonus;
            int manaBonus = ArmazenaMana + 2;
            ArmazenaMana = manaBonus;
           } 
         
          //CAMINHO PARA O BOSS
         
          }  
           if (ArmazenaVida > 0){
             
             System.out.println("");
            System.out.println(boss.descricao); 
            
         while( boss.vida > 0 && ArmazenaVida > 0){
            
            System.out.println("");
            System.out.println("Escolha uma uma das opcoes de ataque!");
            System.out.println("1. Atacar");
            System.out.println("2. Golpe Especial");
            System.out.println("3. Usar Bandagem");
            System.out.println("4. Fugir");
            int escolha1 = scanner.nextInt();
            
            int danoAtacar;
            int danoBandagem;
            int danoEspecial;
            int danoBoss;
            int danoInimigoFinal;
            int armazenaVida;
            int armazenaDano;
            
            
            
             switch (escolha1) { //escolha do menu de habilidades
                 
                case 1: 
                    if (ArmazenaMana > 0){
                    System.out.println("");
            
             personagemEscolhido.Atacar();
            System.out.println("");
            danoAtacar = boss.vida - ArmazenaDano;
            boss.vida = danoAtacar;
            System.out.println("O inimigo recebeu " + ArmazenaDano + " de dano e esta com " + boss.vida+ " de vida!"); // Metodo de Atacar
            
           ArmazenaMana = ArmazenaMana - 1; // retira a energia do personagem apos o ataque
           
        
           
            if (boss.vida > 0 ){
            
            danoBoss = ArmazenaVida - boss.dano;
            ArmazenaVida = danoBoss;
            System.out.println("");
            System.out.println("O seu inimigo te atacou e causou " + boss.dano + " de dano!");
            System.out.println("Agora voce esta com " + ArmazenaVida + " de vida!");
            System.out.println("");
            }
            } else {
                    System.out.println("Voce nao tem mais energia!");
                    }
            break;
            
              //---------------------------------------------------------------------------------------------------------------------------
            
                case 2:
                    if(quantidadeGolpe.quantidadeGP > 0){
                     personagemEscolhido.golpeEspecial();
                    quantidadeGolpe.usarGolpe();
                    System.out.println("");
            int danoGP = boss.vida - quantidadeGolpe.danoEspecial;
            boss.vida = danoGP;
            System.out.println("O inimigo recebeu " + quantidadeGolpe.danoEspecial + " de dano e esta com " + boss.vida + " de vida!");
                             
            //aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
         if (boss.vida > 0 ){   
            danoBoss = ArmazenaVida - boss.dano;
            ArmazenaVida = danoBoss;
            System.out.println("");
            System.out.println("O seu inimigo te atacou e causou " + boss.dano + " de dano!");
            System.out.println("Agora voce esta com " + ArmazenaVida + " de vida!");
            System.out.println("");
            }
                    } else {
                    System.out.println("Voce nao tem mais golpe especial!");
                    }
                    break;
        
               //---------------------------------------------------------------------------------------------------------------------------
                case 3:
                     if (bandagem.quantidadeBandagem > 0) {
                    personagemEscolhido.UsarBandagem(); //mensagem
                    bandagem.BandagemUsada(); //diminui a quantidade
            danoBandagem = ArmazenaVida + bandagem.vidaBandagem; //cura a vida
            ArmazenaVida = danoBandagem; //nova vida
            System.out.println("Voce recebeu mais " + 15 + " de vida!");
            System.out.println("Agora voce esta com " + ArmazenaVida + " de vida!");
            
            if (boss.vida > 0 ){
            danoBoss = ArmazenaVida - boss.dano;
            ArmazenaVida = danoBoss;
            System.out.println("");
            System.out.println("O seu inimigo te atacou e causou " + boss.dano+" de dano");
            System.out.println("Agora voce esta com " + ArmazenaVida + " de vida!");
            System.out.println("");
            }
                   } else {
                    System.out.println("Voce nao tem mais bandagens!");
                    }
                    break;
                   
                    
                case 4:
                    personagemEscolhido.Fugir();
                    System.out.println("Voce nao conseguiu fugir e acabou sendo ferido!");
                   
                    if (boss.vida > 0 ){
            danoBoss = ArmazenaVida - boss.dano;
            ArmazenaVida = danoBoss;
            System.out.println("");
            System.out.println("O seu inimigo te atacou e causou " + boss.dano + " de dano!");
            System.out.println("Agora voce esta com " + ArmazenaVida + " de vida!");
            System.out.println("");
            }
                    break;
                    
                    default:
                    System.out.println("Opcao invalida.");
                    break;
                 }
                    

        }
           } 
           int novainifinal = boss.vida;
           if (novainifinal <= 0) {
            System.out.println("O inimigo foi derrotado!");
            System.out.println("");
            System.out.println("--------A Lenda de Tharion: A Vitoria Sobre o Capeta Infernal--------\n" +
"\n" +
"O ultimo golpe desferido por sua arma ecoa pelo vazio. O Capeta Infernal, uma entidade de"
+ " puro odio e chamas, solta um rugido que abala os ceus daquele mundo metaforico.\n"
+ " Sua figura desmorona em uma explosao de luz e sombras, e um silencio sepulcral toma conta do lugar.\n" +
"Com o inimigo derrotado, voce sente suas forcas retornarem lentamente, como se o proprio mundo ao seu "
+ "redor o estivesse recompensando por sua vitoria. Aos seus pes, onde o Capeta Infernal caiu, surge uma "
+ "pequena esfera brilhante, pulsando com energia. Era o Coracao das Chamas Eternas, "
+ "o nucleo de poder que alimentava o monstro.\n" +
"" +
"Enquanto voce segura a esfera, uma escolha comeca a se formar em sua mente:\n" +
"" +
"Absorver o poder do Coracao, ganhando habilidades sobrenaturais, mas arriscando sua sanidade.\n\n" +
"Destruir o Coracao, livrando o mundo de sua influencia sombria para sempre, mas perdendo uma chance de se tornar mais forte.\n\n" +
"Enquanto decide, o chao comeca a tremer. Ao longe, uma figura encapuzada surge, observando voce de longe. A voz que antes o guiou ecoa novamente:\n" +
"\"-- Sua vitoria foi apenas o inicio, tolo. Este mundo nao e o que parece, e sua verdadeira prova esta apenas comecando...\"\n" +
"\n" +
"O horizonte se distorce, e voce sente que ha algo muito maior aguardando. O que voce fara a seguir?\n" +
"\n\n"
                    + "AGUARDE OS PROXIMOS CAPITULOS...\n"
                    + "              FIM\n"
                    + "-----------------------------------");
            
            } else if (ArmazenaVida <= 0) {
            System.out.println("Voce foi derrotado!");

            }
              
          
    
          
          
    
    
    } // main
    
} //tudo (app

  