/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ArraysList;

import java.util.ArrayList;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        ArrayList<String> carrinho = new ArrayList<>(); // Criar um ArrayList
        
        Bebidas bebidas = new Bebidas();
        Comida comida = new Comida();
        Eletronicos eletronicos = new Eletronicos();
        Roupa roupa = new Roupa();
        Utensilios  utensilio = new Utensilios();
        menu menu = new menu();
        Carrinho carrinho = new Carrinho();
        Preco preco = new Preco();
        
        System.out.println("BEM VINDO AO\n"
                + "\n"
                + "MERCADO GUARINIRI\n");
        
        
        boolean pagamento = false;
        
        while(pagamento == false){
        
        System.out.println(menu.Menu());
        int escolha = scanner.nextInt();
        
        switch(escolha) {
            
            case 1: 
                System.out.println("Voce deseja qual tipo de produto?\n"
                        + "\n"
                        + "1. Comida\n"
                        + "2. Bebidas\n"
                        + "3. Eletronicos\n"
                        + "4.Roupas\n"
                        + "5. Utensilios\n");
                int escolhaP = scanner.nextInt();
                
                if( escolhaP == 1){
                    System.out.println(comida.exibicao());
                    System.out.println("Qual voce deseja? ");
                    int escolhaComida= scanner.nextInt();
                    
                    switch(escolhaComida){
                        
                        case 1: 
                            carrinho.carrinhoP("1. Batata\n");
                            
                           break;
                    }
                }
break;
                        
        
                
        
                        };//switch
        };//while
        
    }//main
};//tudo
