/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AULA4;

public class Violao implements Instrumentos{
    
    @Override
    public void tocar(){
        System.out.println("Bléin blein bleee");
};
    @Override
    public void afinar(){
        System.out.println("Violao sendo afinado");
    }
}

