/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hash;

import hash.database.Conexao;
import hash.view.TelaLogin;

public class App {
    

    public static void main(String[] args) {
        Conexao.conectar();
        
        new TelaLogin().setVisible(true);
    }
}
