/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AULA1;

public class App {
  

    public static void main(String[] args){
        
        String meuNome = "Leleo";
        char minhaInicial = 'L';
         int minhaIdade = 17;
         double minhaAltura = 1.76;
         boolean souAluno = true;
         
           
    System.out.println( "Boa noite Galera, meu nome e " + meuNome + "\ne tenho " + minhaIdade + " \ncom " + minhaAltura + " metros");
    }
}
