/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package superMarket;


import superMarket.database.ConnectionSQL;
import superMarket.view.telaCompras;

public class App {
  
        public static void main(String[] args){
            
        try{
            ConnectionSQL.connected();
            
         
        } catch (Exception e){
            System.out.println("Erro ao criar o banco!" + e.getMessage());
        }
        
        
        new telaCompras().setVisible(true);
    }
}