/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ArrayList;

import java.util.ArrayList;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        
        
        Bebidas bebidas = new Bebidas();
        Comida comida = new Comida();
        Eletronicos eletronicos = new Eletronicos();
        Roupa roupa = new Roupa();
        Utensilios  utensilio = new Utensilios();
        menu menu = new menu();
        Carrinho carrinho = new Carrinho();
        Preco preco = new Preco();
        
        System.out.println("BEM VINDO AO\n"
                + "\n"
                + "MERCADO GUARINIRI\n");
        
        
        boolean pagamento = false;
        
        while(pagamento == false){
        
        System.out.println(menu.Menu());
        int escolha = scanner.nextInt();
        
        switch(escolha) {
            
case 1: 
                System.out.println("Voce deseja qual tipo de produto?\n"
                        + "\n"
                        + "1. Comida\n"
                        + "2. Bebidas\n"
                        + "3. Eletronicos\n"
                        + "4.Roupas\n"
                        + "5. Utensilios\n");
                int escolhaP = scanner.nextInt();
                
                if( escolhaP == 1){
                    System.out.println(comida.exibicao());
                    System.out.println("Qual voce deseja? ");
                    int escolhaComida= scanner.nextInt();
                    
                    switch(escolhaComida){
                        
                        case 1: 
                            carrinho.adicionar("- Carne \n");
                        break;
                        case 2:
                            carrinho.adicionar("- Patel\n");
                        break;
                        case 3:
                            carrinho.adicionar("- Frango\n");
                        break;
                        case 4:
                            carrinho.adicionar("- Arroz\n");
                        break;
                        case 5:
                            carrinho.adicionar("- Feijao\n");
                        break;
                        case 6:
                            carrinho.adicionar("- Batata\n");
                        break;
                    }
                }else if(escolhaP == 2){
                    
                    System.out.println(bebidas.exibicao());          
                    System.out.println("Qual voce deseja? ");
                    int escolhaBebida= scanner.nextInt();
                    
                    switch(escolhaBebida){
                    case 1: 
                            carrinho.adicionar("- Vodka \n");
                        break;
                        case 2:
                            carrinho.adicionar("- Iogurte\n");
                        break;
                        case 3:
                            carrinho.adicionar("- Suco\n");
                        break;
                        case 4:
                            carrinho.adicionar("- Refri\n");
                        break;
                        case 5:
                            carrinho.adicionar("- Whisky\n");
                        break;
                        case 6:
                            carrinho.adicionar("- Agua\n");
                        break;
                    }
}              else if(escolhaP == 3){
    
                      System.out.println(eletronicos.exibicao());          
                    System.out.println("Qual voce deseja? ");
                    int escolhaEletronico= scanner.nextInt();
                    
                    switch(escolhaEletronico){
                    
    case 1: 
        carrinho.adicionar("- Smartphone \n");
        break;
    case 2:
        carrinho.adicionar("- Fone de Ouvido\n");
        break;
    case 3:
        carrinho.adicionar("- Carregador Portátil\n");
        break;
    case 4:
        carrinho.adicionar("- Smartwatch\n");
        break;
    case 5:
        carrinho.adicionar("- Notebook\n");
        break;
    case 6:
        carrinho.adicionar("- Câmera Digital\n");
        break;
}

        } else if(escolhaP == 4){
            
            System.out.println(roupa.exibicao());          
            System.out.println("Qual voce deseja? ");
            int escolhaRoupa= scanner.nextInt();
            switch(escolhaRoupa) {
    case 1: 
        carrinho.adicionar("- Camiseta \n");
        break;
    case 2:
        carrinho.adicionar("- Calça Jeans\n");
        break;
    case 3:
        carrinho.adicionar("- Jaqueta\n");
        break;
    case 4:
        carrinho.adicionar("- Vestido\n");
        break;
    case 5:
        carrinho.adicionar("- Sapato\n");
        break;
    case 6:
        carrinho.adicionar("- Boné\n");
        break;
}

        } else if(escolhaP == 5){
            
            System.out.println(utensilio.exibicao());          
            System.out.println("Qual voce deseja? ");
            int escolhaUtensilio= scanner.nextInt();
            switch(escolhaUtensilio) {
    case 1: 
        carrinho.adicionar("- Panela \n");
        break;
    case 2:
        carrinho.adicionar("- Prato\n");
        break;
    case 3:
        carrinho.adicionar("- Copo\n");
        break;
    case 4:
        carrinho.adicionar("- Talheres\n");
        break;
    case 5:
        carrinho.adicionar("- Cadeira\n");
        break;
    case 6:
        carrinho.adicionar("- Tábua de Corte\n");
        break;
}

        } else{
            System.out.println("ESCOLHA UMA OPCAO VALIDA!");
        }
                        
break;
            case 2:
                carrinho.remover();
                break;
                        
                        case 3:
                            carrinho.vizualizar();
                            break;
                        case 4:
                            carrinho.pagamento();
                            break;
                        case 5:
                            System.out.println("SAINDO...");
                            
                          pagamento = true;
                          break;
                            
                        
        
                
        
                        };//switch
        };//while
        
    }//main
};//tudo
