/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjetoMVC_Tasks;

import ProjetoMVC_Tasks.model.ConexaoSQLite;
import ProjetoMVC_Tasks.model.CriarTabela;
import ProjetoMVC_Tasks.view.TarefaFrom;
import java.sql.Connection;

public class App {
    public static void main(String[] args){
    
        Connection conexao = ConexaoSQLite.conectar();
        CriarTabela.criarTabelaTarefas(conexao); 
        
        new TarefaFrom().setVisible(true);
    
}
}
