/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AULA4;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
       Violaop classUnderTest = newViolaop();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
