/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DESAFIO;

import java.util.Scanner;

public class App{
    public static void main(String[] args) {
    Scanner scanner = new Scanner(System.in);
    
            Paladino paladino = new Paladino();
            Barbaro barbaro = new Barbaro();
            Feiticeiro feiticeiro = new Feiticeiro();
            Inimigo1 inimigo1 = new Inimigo1();
            Inimigo2 inimigo2 = new Inimigo2();
            Boss boss = new Boss();
            Menu menu = new Menu();
            
            
         System.out.println(menu);
         int escolha = scanner.nextInt();
            
            System.out.println("Escolha o nome do seu personagem");
            String nomePersonagem = scanner.nextLine();
    
            System.out.println("Muito prazer " + nomePersonagem + ", Bem vindo ao "
                    + ""
                    + "AVENTURAS AVENTURADAS."
                    + ""
                    + "SUA JORNADA COMEÇA AGORA!");
            
           Habilidades personagemEscolhido = null;
           
           switch(escolha){
               
                 case 1: 
                 personagemEscolhido = paladino;
                 break;
                
                 case 2: 
                 personagemEscolhido = barbaro;
                 break;
                 
                 case 3:
                 personagemEscolhido = feiticeiro;
                 break;
                 
                 default: System.out.println("Escolha alguma opçao válida!!!");
           }
           
           
           
                        
                        
                                
            }
                    
            
            
            
            
            
            
            
            
    }
   
    
    
    
    
}