/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AULA2;

public class App {
        
    
    
    public static void main(String[] args){
        
        Pessoa pessoa1 = new Pessoa("Leandro ", 19 );
        
        pessoa1.apresentar();
    }
    
    
}
